# Generated by Django 5.1.2 on 2024-12-15 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_remove_customuser_whatsapp_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='This field requires less than 320 characters.', max_length=320, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.RegexValidator(message='Email must be from @iitr.ac.in domain.', regex='^[\\w\\.-]+@iitr\\.ac\\.in$')]),
        ),
    ]
