# Generated by Django 5.1.2 on 2024-12-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_teams_FK',
            field=models.ManyToManyField(blank=True, null=True, to='ars.team'),
        ),
    ]
