# Generated by Django 5.1.2 on 2024-12-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0004_alter_assignment_assigned_teams_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader_submission_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ars.submission'),
        ),
    ]
