# Generated by Django 5.1.2 on 2024-12-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0005_alter_team_team_leader_submission_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubtask',
            name='assign_subtask_status_FK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ars.submission'),
        ),
    ]
