# Generated by Django 5.1.2 on 2024-12-24 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0006_alter_assignmentsubtask_assign_subtask_status_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_assignments', to='ars.assignmentsubtask'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_teams_FK',
            field=models.ManyToManyField(blank=True, to='ars.team'),
        ),
        migrations.AlterField(
            model_name='assignmentsubtask',
            name='assign_subtask_reviewer_FK',
            field=models.ManyToManyField(blank=True, related_name='reviewed_subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
