# Generated by Django 5.1.2 on 2024-12-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0007_assignment_assignment_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_assign_creator_FK',
        ),
    ]
