# Generated by Django 5.1.2 on 2024-12-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0008_remove_assignment_is_assign_creator_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='subtask_id_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ars.assignmentsubtask'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team_leader_id_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ars.team'),
        ),
    ]
