# Generated by Django 5.1.2 on 2024-12-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0009_alter_submission_subtask_id_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
