# Generated by Django 5.1.2 on 2024-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0010_attachment_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
